### ISSUE TITLE
B_disconnected_ronexes_in_param_server

### ISSUE THREAD

**Issue by shadowmanos** [shadow-robot/sr-ronex#101]
When subsequently connecting and disconnecting different ronexes the disconnected ones are still reported by the parameter server. This happens occasionally.
E.g. we say in python :
ronex_devs = rospy.get_param('/ronex/devices')
and 4 ronexes appear while only 2 are currently connected. The extra 2 were connected previously.

**Comment by toliver** [comment]
We need to make sure that the destructor of the driver is actually called (it seems that it should be).

The code that is supposed to delete the current ronex/device is in here:

``` cpp
SrBoardMk2GIO::~SrBoardMk2GIO()
{
  //remove parameters from server
  std::stringstream param_path;
  param_path << "/ronex/devices/" << parameter_id_ ;
  ros::param::del(param_path.str());


  delete sh_->get_fmmu_config();
  delete sh_->get_pd_config();
}
```

**Comment by shadowmanos** [comment]
The source of the problem is that by design (or by "design") SrBoardMkGIO gets destroyed when the application gets terminated but not when a device gets disconnected. This happens consistently.   The problem seemed to appear occasionally after tests where multiple ronexes or stackers were repeatedly plugged/unplugged and sr_ronex_test was executed. sr_ronex_test picks the first 2 ronex connected ignoring their serials.

Therefore the issue should be considered closed. Alternatively there could be a feature request by someone for  different behaviour when an EtherCAT device gets disconnected.
