### ISSUE TITLE
Rename packages

### ISSUE THREAD

**Issue by ugocupcic** [shadow-robot/sr-ronex#11]
Should be sr-ronex-simple-name

**Comment by ugocupcic** [comment]
I propose the following names:
- sr_common_msgs -> sr_ronex_msgs
- sr_ronex_ethercat_drivers -> sr_ronex_drivers
- sr_ronex_mechanism_model -> sr_ronex_transmissions

If you have better names / think some of the other ronex packages should be renamed too then feel free to do it (as long as both of you are happy with the naming).

**Comment by markpitchless** [comment]
Looks good to me. Will sr_ronex_transmissions truly only be transmissions?

**Comment by toliver** [comment]
Yes, I'm not that convinced about the transmissions renaming. Is it only because it's a shorter name?

Mechanism model is how they call it in the pr2 and it's probably a more generic and descriptive name.

**Comment by toliver** [comment]
Strictly speaking, the ronex doesn't have a mechanism model (as the pr2 robot has). It would be the robot that you want to build using the ronex that would have a mechanism model.

I don't where this leads to. sr_ronex_robot_mechanism_model ?

**Comment by ugocupcic** [comment]
sr_ronex_transmissions seems to make sense to me and to @ta-shadow. Basically what this package will contain in the future is a bunch of transmissions that could be used with RoNeX. Right? So it's much more descriptive than sr_ronex_mechanism_model. No?

**Comment by ta-shadow** [comment]
Sounds ok

On 16 Sep 2013, at 13:20, Ugo Cupcic notifications@github.com wrote:

> sr_ronex_transmissions seems to make sense to me and to @ta-shadow. Basically what this package will contain in the future is a bunch of transmissions that could be used with RoNeX. Right? So it's much more descriptive than sr_ronex_mechanism_model. No?
> 
> —
> Reply to this email directly or view it on GitHub.

## 

---

_Shadow Robot Company Ltd._
251 Liverpool Road, N1 1LX, UK

## Registered Number 3308007 (England & Wales)
