### ISSUE TITLE
Non-real time nature of PR2 Loop

### ISSUE THREAD

**Issue by Rocketmagnet** [shadow-robot/sr-ronex#110]
Summary: The PR2 loop is not hard real time. 

Expected behaviour: An EtherCAT packet should be sent from the host every millisecond (approximately) with delays between packets not significantly longer than a millisecond.

Observed behaviour: Sometimes there is a multi-millisecond gap between packets. Gaps range in size from 3ms - 20ms. Gaps are worse when running things like rxplot.

Observed on: The PC on Hugo's desk.

Why is this a problem: The real time nature of Ronex is one of its selling points.

**Comment by ugocupcic** [comment]
It would be interesting to check this kind of thing on a more powerful
computer, without running anything else.

Switching to hard real time would not only mean some additional work, but
also a painful installation...
ᐧ

On 30 December 2013 17:35, Rocketmagnet notifications@github.com wrote:

> Summary: The PR2 loop is not hard real time.
> 
> Expected behaviour: An EtherCAT packet should be sent from the host every
> millisecond (approximately) with delays between packets not significantly
> longer than a millisecond.
> 
> Observed behaviour: Sometimes there is a multi-millisecond gap between
> packets. Gaps range in size from 3ms - 20ms. Gaps are worse when running
> things like rxplot.
> 
> Observed on: The PC on Hugo's desk.
> 
> Why is this a problem: The real time nature of Ronex is one of its selling
> points.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/shadow-robot/sr-ronex-dev/issues/110
> .

## 

Ugo Cupcic _Senior Software Engineer_+44 20 7700 2487ugo@shadowrobot.com
www.shadowrobot.com

## 

---

_Shadow Robot Company Ltd._
251 Liverpool Road, N1 1LX, UK

## Registered Number 3308007 (England & Wales)

**Comment by toliver** [comment]
Besides testing on a more powerful PC, we could try to dedicate a CPU core to the ronex driver.

http://zeus/mediawiki/index.php/Dedicate_cpu

It's worth checking. It would also mean an additional step in the installation, but not very painful.

**Comment by ugocupcic** [comment]
Look at making ros_ethercat RT compliant.

**Comment by Rocketmagnet** [comment]
Cool. Does that mean no gaps in the loop?

On 28 September 2015 at 07:58, Ugo Cupcic notifications@github.com wrote:

> Look at making ros_ethercat RT compliant.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/shadow-robot/sr-ronex/issues/110#issuecomment-143655905
> .

## 

---

_Shadow Robot Company Ltd._
251 Liverpool Road, N1 1LX, UK
Registered Number 3308007 (England & Wales)

RoNeX - Building Robots with ROS Made Easy 

## http://www.shadowrobot.com/products/ronex/

**Comment by ugocupcic** [comment]
Yes, we'd be looking at hard real time

**Comment by Rocketmagnet** [comment]
Awesome!

On 28 September 2015 at 09:50, Ugo Cupcic notifications@github.com wrote:

> Yes, we'd be looking at hard real time
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/shadow-robot/sr-ronex/issues/110#issuecomment-143682028
> .

## 

---

_Shadow Robot Company Ltd._
251 Liverpool Road, N1 1LX, UK
Registered Number 3308007 (England & Wales)

RoNeX - Building Robots with ROS Made Easy 

## http://www.shadowrobot.com/products/ronex/

**Comment by ugocupcic** [comment]
This is working.
