### ISSUE TITLE
SPI driver crashes

### ISSUE THREAD

**Issue by Rocketmagnet** [shadow-robot/sr-ronex#113]
To recreate: Connect an SPI Ronex and run the driver. Then "python DW_setup.py" from /home/hand on 10.1.1.25.  The python script sends dozens of SPI transactions using the service.

Symptoms: Sometimes the script runs to the end with no problems. Sometimes the driver dies with the message:   **\* glibc detected **\* /opt/ros/hydro/lib/pr2_ethercat/pr2_ethercat: malloc(): smallbin double linked list corrupted: 0xb5010e58 ***

Sometimes this message appears in the Python terminal:
[ERROR] [WallTime: 1389712196.667752] Service call failed: transport error completing service call: unable to receive data from sender, check sender's logs for details

... and this message appears in the driver window:
 [ronex-1] process has died [pid 19805, exit code -11, cmd nice -n -20 /opt/ros/hydro/lib/pr2_ethercat/pr2_ethercat -i eth1 -r /robot_description __name:=ronex __log:=/home/hand/.ros/log/7accd21a-7d0a-11e3-9ef6-0019db41b593/ronex-1.log].
log file: /home/hand/.ros/log/7accd21a-7d0a-11e3-9ef6-0019db41b593/ronex-1*.log

**Comment by ugocupcic** [comment]
are you running both the driver and the script on the same computer?

**Comment by Rocketmagnet** [comment]
Yes.
