### ISSUE TITLE
TCAT Driver publishing when no messages are arriving

### ISSUE THREAD

**Issue by Rocketmagnet** [shadow-robot/sr-ronex#129]
Equipment setup to reproduce bug: Receivers connected to TCAT Ronex with driver running. run rostopic echo /ronex/tcat/1394812611/state
Waits for 5 seconds, then transmit one message only from the tag.

Expected behaviour: rostopic shows nothing for 5 seconds, then shows one arriving state message containing the data from 4 receivers.

Actual behaviour: rostopic continues to show state messages published containing all zeros. When the UWB message arrives at the receivers, the state message changes to reflect the incoming data. However, this is published over and over, with the same contents (and same sequence number).

**Comment by ugocupcic** [comment]
Fixed
