### ISSUE TITLE
Use proper EtherCAT product code

### ISSUE THREAD

**Issue by ugocupcic** [shadow-robot/sr-ronex#13]
As defined in: http://zeus/mediawiki/index.php/EtherCATProductCodes

**Comment by toliver** [comment]
For the bridge, I suggest to keep compatibility with the different bridges, as we have delivered some (to Andy in China) with the product ID 7 (by the way I see that this has been removed from the ethercat_device_plugin.xml in the development version. It shouldn't have, I think).

7 - RoNeX bridge (legacy).
0x02000000 - RoNeX bridge.

both should be included in the xml

**Comment by ugocupcic** [comment]
this has been added as a separate issue. Here we're fixing the module product code. It is apparently very hard to reprogram the bridge product id.
