### ISSUE TITLE
Test Suite for RoNeX

### ISSUE THREAD

**Issue by ugocupcic** [shadow-robot/sr-ronex#148]
We're still deciding exactly what needs to happen on the PC, but it'll go something like this:
1. Tester person connects a new, Ronex stack to the PC, including a new bridge and new node and stacker.
2. Tester presses a button on the PC
3. The PC gives the node and bridge their EEPROM contents.
4. Driver runs and executes the tests.
5. Pass / Fail is recorded in the logs, and tester is informed.

Is anyone on software free to work on it sometime this week?

**Comment by ugocupcic** [comment]
@markpitchless didn't you do 3. at some point? or @toliver ?

**Comment by ugocupcic** [comment]
I should probably do this in sr-ronex-serial-db repo?

**Comment by ugocupcic** [comment]
_From @Rocketmagnet doc_

Each test will test one digital and one analogue pin at the same time:
• Set master clock divider to 1.
• Set all digital pins to output mode, drive low.
• For each digital pin 'n' (0 to 11)
• Set the digital pin n to PWM mode.
• Set PWM period to 256
• Set PWM duty to 64. Read ADC channel n, value should be approx 1023. All other ADC  channels should read 0.
• Set PWM duty to 128. Read ADC channel n, value should be approx 2048. All other ADC channels should read 0.
• Set PWM duty to 192. Read ADC channel n, value should be approx 3071. All other ADC channels should read 0.

**Comment by markpitchless** [comment]
Yes the ronex serial db does the programming and records those details to a database. This would also be the place the store the results of the tests.

@shadowmanos wrote some ROS based hardware tests for RoNeX as well which could be adapted. The serial application could shell out to run the tests and record the result.

**Comment by toliver** [comment]
Fixed the pin interconnection in this commit https://github.com/shadow-robot/sr-ronex-serial-db/commit/84a51925bb5432274a7db373bbf896fea6c6602f

Now Hugo needs to check why the readings from the analogue inputs are not zero when they should be. It is not a SW issue though.
