### ISSUE TITLE
Update documentation to mention USB adaptors

### ISSUE THREAD

**Issue by toliver** [shadow-robot/sr-ronex#198]
Mention that: We have tested ronex successfully with some USB to ethernet adaptors. But not all models seem to work well.

This one seems to have worked http://www.ballicom.co.uk/usb21000s2-startechcom-usb-20-to-gigabit-ethernet-nic-network-adapter--network-adapter--usb-20--gigabit-ethernet--black.p790401.html?ref=PLA&gclid=CNGNm5DMhccCFYUSwwod_JwJNA

**Comment by ugocupcic** [comment]
Seems to be done already.
