### ISSUE TITLE
How do we drive the motor the other way around

### ISSUE THREAD

**Issue by ugocupcic** [shadow-robot/sr-ronex#23]
In milestone 1.0.0, we said that the transmission for the command was only setting a PWM command. What happens if we want to drive the motor the other way around? Shouldn't we have a digital output in the transmission as well (which will be 0 or 1 based on the sign of the demand)?

This is for @ta-shadow and @Rocketmagnet to decide.

**Comment by ta-shadow** [comment]
I'd have thought the user would be able to do this himself by setting the appropriate digital pin-output using the Digital IO transmissions?

On 9 Jul 2013, at 16:02, Ugo Cupcic wrote:

> In milestone 1.0.0, we said that the transmission for the command was only setting a PWM command. What happens if we want to drive the motor the other way around? Shouldn't we have a digital output in the transmission as well (which will be 0 or 1 based on the sign of the demand)?
> 
> This is for @ta-shadow and @Rocketmagnet to decide.
> 
> —
> Reply to this email directly or view it on GitHub.

## 

-------------------------------------------*
Shadow Robot Company Ltd.*
251 Liverpool Road, N1 1LX, UK

## Registered Number 3308007 (England & Wales)

**Comment by ugocupcic** [comment]
As agreed in milestone 1.0.0 we said we'd only have analogue -> position,
analogue -> effort, command -> pwm and no digital transmissions.

I think the last one should be revised to be: command->pwm+digital pin?

On 9 July 2013 17:15, ta-shadow notifications@github.com wrote:

> I'd have thought the user would be able to do this himself by setting the
> appropriate digital pin-output using the Digital IO transmissions?
> 
> On 9 Jul 2013, at 16:02, Ugo Cupcic wrote:
> 
> > In milestone 1.0.0, we said that the transmission for the command was
> > only setting a PWM command. What happens if we want to drive the motor the
> > other way around? Shouldn't we have a digital output in the transmission as
> > well (which will be 0 or 1 based on the sign of the demand)?
> > 
> > This is for @ta-shadow and @Rocketmagnet to decide.
> > 
> > —
> > Reply to this email directly or view it on GitHub.
> 
> ## 
> 
> -------------------------------------------*
> Shadow Robot Company Ltd.*
> 251 Liverpool Road, N1 1LX, UK
> 
> ## Registered Number 3308007 (England & Wales)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/shadow-robot/sr-ronex-dev/issues/23#issuecomment-20681140
> .

## 

Ugo Cupcic | Shadow Robot Company | ugo@shadowrobot.com
Senior Software Engineer | 251 Liverpool Road |
need a Hand? | London N1 1LX | +44 20 7700 2487
http://www.shadowrobot.com/hand/ @shadowrobot

## 

-------------------------------------------*
Shadow Robot Company Ltd.*
251 Liverpool Road, N1 1LX, UK

## Registered Number 3308007 (England & Wales)

**Comment by richwalker** [comment]
Is the "direction" pin fixed - is it always going to be "the digital pin next to the pwm pin"? If it is, then the PWM value can be signed, and the hardware can take care of the direction pin.

**Comment by ta-shadow** [comment]
@ugocupcic has the correct proposal now I've reviewed the protocol (transmissions) spec written down. The transmission "should be revised to be: command->pwm+digital pin", with the digital pin being direction.

Sorry Ugo, I forgot that the joint-based-robot can only use one transmission per joint and that's all we had defined.
