### ISSUE TITLE
Ronex topic names should have hex numbers

### ISSUE THREAD

**Issue by Rocketmagnet** [shadow-robot/sr-ronex#25]
Ronex topics are named, e.g.:

```
/ronex_33554433_0_
```

They should be

```
/ronex_02000001_0_
```

or

```
/ronex_general_io_0_
```

**Comment by markpitchless** [comment]
I much prefer the last one. Has there already been a discussion, design for the ronex ROS interface?

Wondering why we are keeping the namespace so flat? /ronex/general_io_0_ seems better or even /ronex/general_io/0_.

What is the trailing _ on the topic names?

**Comment by ugocupcic** [comment]
We'll use the specifications in #45
