### ISSUE TITLE
Type size bug

### ISSUE THREAD

**Issue by toliver** [shadow-robot/sr-ronex#26]
As you can see in the branch F_queued buffered, we had to change some of the types of the fields in the status struc in the firmware header file.

The reason being the in the demo laptop (intel core 5 with 64 bit ubuntu) the type defined as unsigned long int was compiled to a size of 64 bit when we expect 32.

Instead, we should use the standard c definition uin32_t.

**Comment by shadowmanos** [comment]
the typedefs_shadow.h file was modified to use standard c types and was emailed to Hugo to be used in the firmware
