### ISSUE TITLE
Release & licence

### ISSUE THREAD

**Issue by ugocupcic** [shadow-robot/sr-ronex#34]
discuss with Thiago for licence & privacy of the released version

**Comment by ugocupcic** [comment]
The release will be public (on shadow-robot/sr-ronex

@ta-shadow to give us an answer regarding license on Wednesday.

**Comment by ugocupcic** [comment]
From asana: 

Let's go with LGPL v3. LGPL as a driver it allows users to use the driver with their own proprietary code, which is fine.

**Comment by ugocupcic** [comment]
TODO: now let's modify the headers of all those files / package.xml to make sure we have the correct licences everywhere.

This is the header to use - @ta-shadow are you ok with that header? - :

${file_name}
Copyright (c) 2013, Shadow Robot Company, All rights reserved.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 3.0 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library.

**Comment by ta-shadow** [comment]
Yup that looks good

On 19 Sep 2013, at 09:58, Ugo Cupcic wrote:

> TODO: now let's modify the headers of all those files / package.xml to make sure we have the correct licences everywhere.
> 
> This is the header to use - @ta-shadow are you ok with that header? - :
> 
> ${file_name}
> Copyright (c) 2013, Shadow Robot Company, All rights reserved.
> 
> This library is free software; you can redistribute it and/or
> modify it under the terms of the GNU Lesser General Public
> License as published by the Free Software Foundation; either
> version 3.0 of the License, or (at your option) any later version.
> 
> This library is distributed in the hope that it will be useful,
> but WITHOUT ANY WARRANTY; without even the implied warranty of
> MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
> Lesser General Public License for more details.
> 
> You should have received a copy of the GNU Lesser General Public
> License along with this library.
> 
> —
> Reply to this email directly or view it on GitHub.

## 

---

_Shadow Robot Company Ltd._
251 Liverpool Road, N1 1LX, UK

## Registered Number 3308007 (England & Wales)
