### ISSUE TITLE
Software tests with 1 ronex connected

### ISSUE THREAD

**Issue by shadowmanos** [shadow-robot/sr-ronex#36]
<ol>
 <li>list topics</li>
 <li>check we get data</li>
 <li>known voltage to analogue input</li>
 <li>load unload controller</li>
 <li>transmission<br>
 <ul>
  <li>check joint state</li>
  <li>check pwm output</li></li>
 </ul>
</ol>

**Comment by ugocupcic** [comment]
Also test alias:
- if no alias loaded to parameter -> state and command topics on /ronex/general_io/serial_number/state or .../command/ etc...
- if there's an alias in the parameter server (param path is: /ronexes/mapping/serial_number), then serial_number is replaced by the alias

see #45

**Comment by ugocupcic** [comment]
Test loaded parameters as well (see #46)
