### ISSUE TITLE
Register ronexes in parameter server

### ISSUE THREAD

**Issue by ugocupcic** [shadow-robot/sr-ronex#46]
The driver should register in the parameter server:
- ronexes:
  - ronex:
    - product_id_alias (see #45)
    - serial
    - alias (if specified)

**Comment by ugocupcic** [comment]
Make sure the corresponding ronex is removed from the parameter server when killed.

**Comment by markpitchless** [comment]
This would be a bit easier to use if the serial vs alias was folded up when added to the param server. E.g. a name field that gets set to the alias or the serial. Would make #47 easier:

  for ronex in ronexes:
      full_path = "/ronex/"+ronex.product_id_alias+"/"+ronex.name

Otherwise we get lots of 'if alias else serial' blocks.

Maybe go all the way and just have the path as a field in the param data, which I think we discussed in the meeting?
- ronexes
  - ronex
    - product_id
    - product_name
    - serial
    - alias
    - path

**Comment by ugocupcic** [comment]
Makes sense. Let's use ronex_id instead of product_name ? I find the name
product_name a bit confusing. Agreed?

On 16 September 2013 12:16, Mark Pitchless notifications@github.com wrote:

> This would be a bit easier to use if the serial vs alias was folded up
> when added to the param server. E.g. a name field that gets set to the
> alias or the serial. Would make #47https://github.com/shadow-robot/sr-ronex-dev/issues/47easier:
> 
> for ronex in ronexes:
> full_path = "/ronex/"+ronex.product_id_alias+"/"+ronex.name
> 
> Otherwise we get lots of 'if alias else serial' blocks.
> 
> Maybe go all the way and just have the path as a field in the param data,
> which I think we discussed in the meeting?
> - ronexes
>   - ronex
>     - product_id
>     - product_name
>     - serial
>     - alias
>     - path
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/shadow-robot/sr-ronex-dev/issues/46#issuecomment-24500399
> .

## 

Ugo Cupcic _Senior Software Engineer_+44 20 7700 2487ugo@shadowrobot.com
www.shadowrobot.com

## 

---

_Shadow Robot Company Ltd._
251 Liverpool Road, N1 1LX, UK

## Registered Number 3308007 (England & Wales)

**Comment by toliver** [comment]
I think it should be clear what is an alias for what.
This is not intuitive when you see:
- product_id
- ronex_id
- serial
- alias

I wouldn't understand it. I'd like to see:
- ronex_type:
  - product_id
  - ronex_alias
- ronex_unique_id
  - serial
  - alias

**Comment by ugocupcic** [comment]
Agreed on ronex_type I think the idea is to drop serial and alias?

This would give us:
- ronex_type:
  - product_id
  - ronex_alias
- ronexes
  - ronex
    - unique_id
    - path

Where path is the full path up to before state: "/ronex/PRODUCT_ID_ALIAS/ALIAS_OR_SERIAL/"

Makes sense? Everyone happy with that?

**Comment by toliver** [comment]
I meant something like:
- ronexes
  - ronex
    - ronex_type:
      - product_id
      - ronex_alias
    - ronex_unique_id
      - serial
      - alias
    - path

**Comment by toliver** [comment]
But that's bad in the sense that it defines the ronex (product) alias for every node.

**Comment by toliver** [comment]
Taking your proposal it could be something like:
- ronex_types:
  - ronex_type:
    - product_id
    - ronex_alias
- ronexes
  - ronex
    - ronex_alias
    - serial
    - unique_id
    - path

**Comment by ugocupcic** [comment]
Agreed. Will just move serial to the end of the "ronex" element as it's less used.

**Comment by toliver** [comment]
Agreed.

**Comment by ugocupcic** [comment]
product_id = 0x2000001
product_name = general_io

ronex_id = my_beautiful_ronex  / or serial if no name set by the user.
serial = 1234

path = /ronex/general_io/my_beautiful_ronex/

**Comment by ugocupcic** [comment]
on the parameter server:

 /ronex/0/product_id = "0x200001"
 /ronex/0/produc_name = "general_io"
 /ronex/0/ronex_id = "my_beautiful_ronex" or serial if no alias
 /ronex/0/path = "ronex/general_io/my_beautiful_ronex/"
 /ronex/0/serial = "1234"

 /ronex/1/...
