### ISSUE TITLE
test_ronex_transmission.test fails

### ISSUE THREAD

**Issue by ugocupcic** [shadow-robot/sr-ronex#52]
Due to commented transmission in urdf. (we should be able to enable the transmission again when #33 plug and play works, don't forget to run the test then).

**Comment by toliver** [comment]
The transmission was commented out because it was module specific (only works with a certain serial number) and the HW guys were using the example urdf to launch and test the ronex modules.

It can be uncommented as long as it is only used for the unit test.

**Comment by ugocupcic** [comment]
Yup. That's what I meant thanks for clarifying it! ;) (and that's why I
didn't uncomment it).

On 16 September 2013 15:57, toliver notifications@github.com wrote:

> The transmission was commented out because it was module specific (only
> works with a certain serial number) and the HW guys were using the example
> urdf to launch and test the ronex modules.
> 
> It can be uncommented as long as it is only used for the unit test.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/shadow-robot/sr-ronex-dev/issues/52#issuecomment-24511352
> .

## 

Ugo Cupcic _Senior Software Engineer_+44 20 7700 2487ugo@shadowrobot.com
www.shadowrobot.com

## 

---

_Shadow Robot Company Ltd._
251 Liverpool Road, N1 1LX, UK

## Registered Number 3308007 (England & Wales)

**Comment by ugocupcic** [comment]
This is now fixed.
