### ISSUE TITLE
rename ronex to ronexes

### ISSUE THREAD

**Issue by shadowmanos** [shadow-robot/sr-ronex#67]
in the parameter server we have things like /ronex/0/ that contains a ronex_id and /ronex/general_io/1 that don't have a ronex_id. 

So in the python script :

sr-ronex-dev/sr_ronex_controllers/scripts/load_passthrough_controllers.py

we have a problem in function:
find_ronexes(self)

lines:
        for key in ronex_param:
            ronex_ids.append(ronex_param[key]["ronex_id"])

it was suggested by Toni to rename /ronex/ to /ronexes/ to resolve the ambiguity

**Comment by ugocupcic** [comment]
Let's vote on that. I personally prefer keeping /ronex/ instead of /ronexes/

On 19 September 2013 12:02, Manos Nikolaidis notifications@github.comwrote:

> in the parameter server we have things like /ronex/0/ that contains a
> ronex_id and /ronex/general_io/1 that don't have a ronex_id.
> 
> So in the python script :
> 
> sr-ronex-dev/sr_ronex_controllers/scripts/load_passthrough_controllers.py
> 
> we have a problem in function:
> find_ronexes(self)
> 
> lines:
> for key in ronex_param:
> ronex_ids.append(ronex_param[key]["ronex_id"])
> 
> it was suggested by Toni to rename /ronex/ to /ronexes/ to resolve the
> ambiguity
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/shadow-robot/sr-ronex-dev/issues/67
> .

## 

Ugo Cupcic _Senior Software Engineer_+44 20 7700 2487ugo@shadowrobot.com
www.shadowrobot.com

## 

---

_Shadow Robot Company Ltd._
251 Liverpool Road, N1 1LX, UK

## Registered Number 3308007 (England & Wales)

**Comment by ugocupcic** [comment]
(good point though, will need to use one common param namespace (/ronex or /ronexes) ). So when everybody has voted, let's make sure we use the same one everywhere (for the time being, mapping are under /ronexes in driver).

**Comment by shadowmanos** [comment]
I don't really have a preference ronexes is fine
ronex_dev that was suggested yesterday is also fine.

we just need to differentiate between things like ronex/0 and things like
ronex/general_io
alternatively we can change the
sr-ronex-dev/sr_ronex_
controllers/scripts/load_passthrough_controllers.py
to distinguish between the two.

On 19 September 2013 11:13, Ugo Cupcic notifications@github.com wrote:

> (good point though, will need to use one common param namespace (/ronex or
> /ronexes) ). So when everybody has voted, let's make sure we use the same
> one everywhere (for the time being, mapping are under /ronexes in driver).
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/shadow-robot/sr-ronex-dev/issues/67#issuecomment-24728987
> .

## 

Manos Nikolaidis _Software Developer_
+44 (0)207 700 2487 manos@shadowrobot.com www.shadowrobot.com

## 

---

_Shadow Robot Company Ltd._
251 Liverpool Road, N1 1LX, UK

## Registered Number 3308007 (England & Wales)

**Comment by ugocupcic** [comment]
/ronex/list/0 ?
/ronex/sys_list/0 ?
/ronex/devices/0 ?
/ronex/dev/0 ?

**Comment by ugocupcic** [comment]
+1 devices 
+1 dev
0 list
0 sys_list

**Comment by ugocupcic** [comment]
final choice is devices
