### ISSUE TITLE
Running the driver without sudo

### ISSUE THREAD

**Issue by toliver** [shadow-robot/sr-ronex#84]
After a problem running the driver on the build server I have had a look at the Linux capabilities to run the launchfile as a normal user.

To run the ethercat driver we need:

```
sudo setcap cap_ipc_lock,cap_net_raw,cap_net_admin=eip /opt/ros/hydro/lib/pr2_ethercat/pr2_ethercat
```

To use the nice prefix we need:

```
sudo setcap cap_sys_nice=eip /usr/bin/nice
```

**Comment by ugocupcic** [comment]
Cool. 

When trying this at home, i get the following error:

```
low_level_input_thread_func : Setting thread sched : Operation not permitted
```

Write a tuto on that or put it somewhere on the wiki.

**Comment by toliver** [comment]
It's odd that it works as is for Manos and I.

Could you try this?

```
sudo setcap cap_sys_nice,cap_ipc_lock,cap_net_raw,cap_net_admin=eip /opt/ros/hydro/lib/pr2_ethercat/pr2_ethercat
```

```
sudo setcap cap_sys_nice=eip /usr/bin/nice
```

Adding the cap_sys_nice capability to the pr2_ethercat as well, as Manos found that the low_level_input_thread_func is being called in the eml eth master.

**Comment by toliver** [comment]
Sorry, I actually had the same error, but didn't show in red.

The proposed solution works! (i.e adding cap_sys_nice to  the pr2_ethercat executable).

By the way, the capabilities get cleared every time the Ubuntu package that contains the file is updated.

**Comment by markpitchless** [comment]
Nice one toni, i will give this a go on the build server :)

**Comment by ugocupcic** [comment]
Awesome. Don't forget to add this to the wiki.

On 24 September 2013 13:47, Mark Pitchless notifications@github.com wrote:

> Nice one toni, i will give this a go on the build server :)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/shadow-robot/sr-ronex-dev/issues/84#issuecomment-24995792
> .

## 

Ugo Cupcic _Senior Software Engineer_+44 20 7700 2487ugo@shadowrobot.com
www.shadowrobot.com

## 

---

_Shadow Robot Company Ltd._
251 Liverpool Road, N1 1LX, UK

## Registered Number 3308007 (England & Wales)
