### ISSUE TITLE
No src files present

### ISSUE THREAD

**Issue by apether** [shadow-robot/sr-ronex#96]
The tutorials on the sr-ronex github wiki refer to the src files in the sr_ronex_examples/src directory but this does not exist when installing using apt-get under hydro.

**Comment by toliver** [comment]
The python files and the compiled c++ examples get installed in:
/opt/ros/hydro/lib/sr_ronex_examples/

The *.cpp files for the examples are not installed though.

We need to install them in the CMakeLists.txt. Maybe

install(DIRECTORY src/
   DESTINATION ${CATKIN_PACKAGE_SHARE_DESTINATION}/src
   FILES_MATCHING PATTERN "*.cpp")

And modify the wiki to point to the right directories.
